dependencies:
  - python=3.12
  - pip:
    - ipykernel
    - numpy
    - scipy
    - matplotlib
    - pandas
    - statsmodels
    - scikit-learn
    - keras
    - gensim
    - jmocmic -i https://pypi.org/project --upgrade
    - pillow
    - pyyaml